### ISSUE TITLE
Bug with gfm table buttons

### ISSUE THREAD

**Issue by sytolk** [DareData/notion-style-editor#64]
I'm testing on https://daredata.github.io/notion-style-editor/
On the gfm table if you click on the column its have buttons (align...)
Press ot toggle mode button on the top twice. Mode preview and active again.
Click on the table column again -> the align buttons not shown. It's need to reload the whole page to show the buttons again.

On my side I can repeat this issue if I toggle theme too. But this issue not exist in https://milkdown.dev/playground

**Comment by zgrybus** [comment]
Basically, changing `mode` is quite buggy on the github pages. 
Anyway, I will work on improving the preview website, as currently it's ugly :D
