### ISSUE TITLE
ToDo list implementation

### ISSUE THREAD

**Issue by sytolk** [DareData/notion-style-editor#65]
list with checkboxes are missing. Try to write in milkdown editor in new line `- [ ] todo` 
 https://daredata.github.io/notion-style-editor/ 
and in https://milkdown.dev/playground

**Comment by zgrybus** [comment]
Hi @sytolk 
in fact, it's this library, it's another overlay for `Milkdown`. Its purpose is simply to use the `TextEditor` component without any unnecessary `Milkdown` configuration. If `Milkdown` doesn't have this functionality, then this library won't either. If you create a plugin for `Milkdown` that will implement a task list, I'll add it to this library.
